filter:
  paths:
    - yturl.py

checks:
  python:
    basic_abstract_class_instantiated: true
    basic_assert_on_tuple: true
    basic_dangerous_default_value: true
    basic_duplicate_argument_name: true
    basic_duplicate_key: true
    basic_eval_used: true
    basic_function_redefined: true
    basic_lost_exception: true
    basic_missing_docstring: true
    basic_missing_module_attribute: true
    basic_missing_reversed_argument: true
    basic_not_in_loop: true
    basic_old_raise_syntax: true
    basic_unnecessary_lambda: true
    basic_unreachable: true
    basic_useless_else_on_loop: true
    basic_yield_outside_function: true
    classes_abstract_method: true
    classes_arguments_differ: true
    classes_attribute_defined_outside_init: true
    classes_bad_classmethod_argument: true
    classes_bad_context_manager: true
    classes_bad_mcs_classmethod_argument: true
    classes_bad_mcs_method_argument: true
    classes_bad_staticmethod_argument: true
    classes_interface_is_not_class: true
    classes_missing_interface_method: true
    classes_no_init: true
    classes_no_self_argument: true
    classes_no_self_use: true
    classes_non_iterator_returned: true
    classes_non_parent_init_called: true
    classes_protected_access: true
    classes_signature_differs: true
    classes_super_init_not_called: true
    classes_valid_slots: true
    code_rating: true
    design_abstract_class_little_used: true
    design_abstract_class_not_used: true
    design_interface_not_implemented: true
    duplicate_code: true
    exceptions_bare_except: true
    exceptions_broad_except: true
    exceptions_catching_non_exception: true
    exceptions_notimplemented_raised: true
    exceptions_pointless_except: true
    exceptions_raising_bad_type: true
    exceptions_raising_non_exception: true
    format_bad_whitespace: true
    format_line_too_long:
      max_length: '80'
    format_lowercase_l_suffix: true
    format_missing_final_newline: true
    format_multiple_statements: true
    format_superfluous_parens: true
    format_trailing_whitespace: true
    format_unnecessary_semicolon: true
    imports_cyclic_import: true
    imports_deprecated_module: true
    imports_import_error: true
    imports_import_self: true
    imports_reimported: true
    imports_relative_import: true
    imports_wildcard_import: true
    logging_format_truncated: true
    logging_not_lazy: true
    logging_too_few_args: true
    logging_too_many_args: true
    logging_unsupported_format: true
    newstyle_bad_super_call: true
    open_mode_bad_open_mode: true
    string_bad_format_string_key: true
    string_bad_str_strip_call: true
    string_constant_anomalous_backslash_in_string: true
    string_constant_anomalous_unicode_escape_in_string: true
    string_format_needs_mapping: true
    string_missing_format_string_key: true
    typecheck_assignment_from_no_return: true
    typecheck_assignment_from_none: true
    typecheck_maybe_no_member: true
    typecheck_no_member: true
    typecheck_no_value_for_parameter: true
    typecheck_not_callable: true
    typecheck_too_many_function_args: true
    variables_global_at_module_level: true
    variables_global_statement: true
    variables_global_variable_not_assigned: true
    variables_global_variable_undefined: true
    variables_invalid_all_object: true
    variables_redefine_in_handler: true
    variables_redefined_builtin: true
    variables_redefined_outer_name: true
    variables_unbalanced_tuple_unpacking: true
    variables_undefined_all_variable: true
    variables_undefined_loop_variable: true
    variables_undefined_variable: true
    variables_unused_variable: true
    variables_unused_wildcard_import: true
    variables_used_before_assignment: true
