language: python

env:
  - TOXENV=system

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

  # Allowed to fail
  - '3.7-dev'
  - 'nightly'

install: pip install tox

script:
  - 'tox'

after_success:
  - 'if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e coverage; fi'

matrix:
  fast_finish: true
  allow_failures:
    - python: '3.7-dev'
    - python: 'nightly'

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
