language: python
install:
  - pip install -r docs/requirements.txt
  - pip install -r tests/requirements.txt
python:
  - 2.7
  - 3.3
  - 3.4
  - nightly
script:
  - nosetests --with-coverage

  # Our doctests are authoritative only on 3.4
  - '[[ $TRAVIS_PYTHON_VERSION != 3.4 ]] || (cd docs && make doctest)'
after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

# Enable container based Travis CI infrastructure
# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
