language: python

env:
  - TOXENV=system

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install: pip install tox

script:
  - 'tox'

after_success:
  - 'if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e coverage; fi'

matrix:
  fast_finish: true

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
