language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

  # Allowed to fail
  - '3.7-dev'
  - 'nightly'

install: pip install tox

script:
  - 'tox'

matrix:
  fast_finish: true
  allow_failures:
    - python: '3.7-dev'
    - python: 'nightly'
  include:
    - python: '3.6'
      env: TOXENV=coverage

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
